name: unsplash_wallpaper
description: 壁纸应用.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  cached_network_image: ^3.3.0
  flutter_staggered_grid_view: ^0.7.0
  photo_view: ^0.14.0
  share_plus: ^7.2.1
  saver_gallery: ^3.0.1
  permission_handler: ^11.3.0
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true 